services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin_data:/pgadmin
    networks:
      - NBP-APP
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin4-http.entrypoints=web"
        - "traefik.http.routers.pgadmin4-http.rule=Host(`pgadmin.aymconsultores.es`)"
        - "traefik.http.routers.pgadmin4.entrypoints=websecure"
        - "traefik.http.routers.pgadmin4.rule=Host(`pgadmin.aymconsultores.es`)"
        - "traefik.http.routers.pgadmin4-http.middlewares=pgadmin4-https@docker"
        - "traefik.http.middlewares.pgadmin4-https.redirectscheme.scheme=https"
        - "traefik.http.routers.pgadmin4.tls=true"
        - "traefik.http.routers.pgadmin4.tls.certresolver=le"
        - "traefik.http.services.pgadmin4.loadbalancer.server.port=80"

networks:
  NBP-APP:

volumes:
  pgadmin_data:

#docker stack deploy --compose-file=pgadmin.yml pgadmin
#https://fernandezmejias.medium.com/adding-postgrsql-and-pgadmin-as-services-in-traefik-2-x-d0c2646b1413